/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ObraRouteImport } from './routes/obra'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ObraTemaRouteImport } from './routes/obra.tema'
import { Route as ObraSimbolicoRouteImport } from './routes/obra.simbolico'
import { Route as ObraRecursosRouteImport } from './routes/obra.recursos'
import { Route as ObraOpinionRouteImport } from './routes/obra.opinion'
import { Route as ObraIntencionRouteImport } from './routes/obra.intencion'
import { Route as ObraContextoRouteImport } from './routes/obra.contexto'
import { Route as ObraAutorRouteImport } from './routes/obra.autor'

const ObraRoute = ObraRouteImport.update({
  id: '/obra',
  path: '/obra',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ObraTemaRoute = ObraTemaRouteImport.update({
  id: '/tema',
  path: '/tema',
  getParentRoute: () => ObraRoute,
} as any)
const ObraSimbolicoRoute = ObraSimbolicoRouteImport.update({
  id: '/simbolico',
  path: '/simbolico',
  getParentRoute: () => ObraRoute,
} as any)
const ObraRecursosRoute = ObraRecursosRouteImport.update({
  id: '/recursos',
  path: '/recursos',
  getParentRoute: () => ObraRoute,
} as any)
const ObraOpinionRoute = ObraOpinionRouteImport.update({
  id: '/opinion',
  path: '/opinion',
  getParentRoute: () => ObraRoute,
} as any)
const ObraIntencionRoute = ObraIntencionRouteImport.update({
  id: '/intencion',
  path: '/intencion',
  getParentRoute: () => ObraRoute,
} as any)
const ObraContextoRoute = ObraContextoRouteImport.update({
  id: '/contexto',
  path: '/contexto',
  getParentRoute: () => ObraRoute,
} as any)
const ObraAutorRoute = ObraAutorRouteImport.update({
  id: '/autor',
  path: '/autor',
  getParentRoute: () => ObraRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/obra': typeof ObraRouteWithChildren
  '/obra/autor': typeof ObraAutorRoute
  '/obra/contexto': typeof ObraContextoRoute
  '/obra/intencion': typeof ObraIntencionRoute
  '/obra/opinion': typeof ObraOpinionRoute
  '/obra/recursos': typeof ObraRecursosRoute
  '/obra/simbolico': typeof ObraSimbolicoRoute
  '/obra/tema': typeof ObraTemaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/obra': typeof ObraRouteWithChildren
  '/obra/autor': typeof ObraAutorRoute
  '/obra/contexto': typeof ObraContextoRoute
  '/obra/intencion': typeof ObraIntencionRoute
  '/obra/opinion': typeof ObraOpinionRoute
  '/obra/recursos': typeof ObraRecursosRoute
  '/obra/simbolico': typeof ObraSimbolicoRoute
  '/obra/tema': typeof ObraTemaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/obra': typeof ObraRouteWithChildren
  '/obra/autor': typeof ObraAutorRoute
  '/obra/contexto': typeof ObraContextoRoute
  '/obra/intencion': typeof ObraIntencionRoute
  '/obra/opinion': typeof ObraOpinionRoute
  '/obra/recursos': typeof ObraRecursosRoute
  '/obra/simbolico': typeof ObraSimbolicoRoute
  '/obra/tema': typeof ObraTemaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/obra'
    | '/obra/autor'
    | '/obra/contexto'
    | '/obra/intencion'
    | '/obra/opinion'
    | '/obra/recursos'
    | '/obra/simbolico'
    | '/obra/tema'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/obra'
    | '/obra/autor'
    | '/obra/contexto'
    | '/obra/intencion'
    | '/obra/opinion'
    | '/obra/recursos'
    | '/obra/simbolico'
    | '/obra/tema'
  id:
    | '__root__'
    | '/'
    | '/obra'
    | '/obra/autor'
    | '/obra/contexto'
    | '/obra/intencion'
    | '/obra/opinion'
    | '/obra/recursos'
    | '/obra/simbolico'
    | '/obra/tema'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ObraRoute: typeof ObraRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/obra': {
      id: '/obra'
      path: '/obra'
      fullPath: '/obra'
      preLoaderRoute: typeof ObraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obra/tema': {
      id: '/obra/tema'
      path: '/tema'
      fullPath: '/obra/tema'
      preLoaderRoute: typeof ObraTemaRouteImport
      parentRoute: typeof ObraRoute
    }
    '/obra/simbolico': {
      id: '/obra/simbolico'
      path: '/simbolico'
      fullPath: '/obra/simbolico'
      preLoaderRoute: typeof ObraSimbolicoRouteImport
      parentRoute: typeof ObraRoute
    }
    '/obra/recursos': {
      id: '/obra/recursos'
      path: '/recursos'
      fullPath: '/obra/recursos'
      preLoaderRoute: typeof ObraRecursosRouteImport
      parentRoute: typeof ObraRoute
    }
    '/obra/opinion': {
      id: '/obra/opinion'
      path: '/opinion'
      fullPath: '/obra/opinion'
      preLoaderRoute: typeof ObraOpinionRouteImport
      parentRoute: typeof ObraRoute
    }
    '/obra/intencion': {
      id: '/obra/intencion'
      path: '/intencion'
      fullPath: '/obra/intencion'
      preLoaderRoute: typeof ObraIntencionRouteImport
      parentRoute: typeof ObraRoute
    }
    '/obra/contexto': {
      id: '/obra/contexto'
      path: '/contexto'
      fullPath: '/obra/contexto'
      preLoaderRoute: typeof ObraContextoRouteImport
      parentRoute: typeof ObraRoute
    }
    '/obra/autor': {
      id: '/obra/autor'
      path: '/autor'
      fullPath: '/obra/autor'
      preLoaderRoute: typeof ObraAutorRouteImport
      parentRoute: typeof ObraRoute
    }
  }
}

interface ObraRouteChildren {
  ObraAutorRoute: typeof ObraAutorRoute
  ObraContextoRoute: typeof ObraContextoRoute
  ObraIntencionRoute: typeof ObraIntencionRoute
  ObraOpinionRoute: typeof ObraOpinionRoute
  ObraRecursosRoute: typeof ObraRecursosRoute
  ObraSimbolicoRoute: typeof ObraSimbolicoRoute
  ObraTemaRoute: typeof ObraTemaRoute
}

const ObraRouteChildren: ObraRouteChildren = {
  ObraAutorRoute: ObraAutorRoute,
  ObraContextoRoute: ObraContextoRoute,
  ObraIntencionRoute: ObraIntencionRoute,
  ObraOpinionRoute: ObraOpinionRoute,
  ObraRecursosRoute: ObraRecursosRoute,
  ObraSimbolicoRoute: ObraSimbolicoRoute,
  ObraTemaRoute: ObraTemaRoute,
}

const ObraRouteWithChildren = ObraRoute._addFileChildren(ObraRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ObraRoute: ObraRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
